### ISSUE TITLE
End-to-end tests appear broken

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#317]
Please do work for this task in a branch called issue-317.

```shell
meteor npm run test-e2e

> radgrad2@ test-e2e /Users/philipjohnson/github/radgrad/radgrad2/app
> testcafe chrome:headless imports/ui/**/*.test-e2e.ts

 Running tests in:
 - Chrome 85.0.4183.121 / macOS 10.15.6

 Student Pages
 ✖ Menu Bars

   1) - Error in fixture.beforeEach hook -
      A request to "http://localhost:3200/" has failed.
      Use quarantine mode to perform additional attempts to execute this test.
      You can find troubleshooting information for this issue at "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".

      Error details:
      Failed to find a DNS-record for the resource at "http://localhost:3200/".

      Browser: Chrome 85.0.4183.121 / macOS 10.15.6

         29 |  studentMentorSpaceAskQuestionWidget,
         30 |  studentMentorSpaceMentorDirectoryWidget,
         31 |} from '../components/student/student-widget-names';
         32 |
         33 |export const adminLogin = async ({ email, password, browser }) => {
       > 34 |  await browser.click(Selector('div.ui.top.right.pointing.dropdown').child('div.text'));
         35 |  await browser.click(Selector('#admin'));
         36 |  await browser.typeText(Selector('input[name=email]'), email);
         37 |  await browser.typeText(Selector('input[name=password]'), password);
         38 |  await browser.click(Selector('div.field button.ui.button'));
         39 |};

         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/test-helpers/e2e.ts:34:17)
         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/test-helpers/e2e.ts:8:71)
         at __awaiter (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/test-helpers/e2e.ts:4:12)
         at Object.exports.adminLogin (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/test-helpers/e2e.ts:33:66)
         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/pages/student/StudentPages.test-e2e.ts:57:11)
         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/pages/student/StudentPages.test-e2e.ts:8:71)
         at __awaiter (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/pages/student/StudentPages.test-e2e.ts:4:12)
         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/pages/student/StudentPages.test-e2e.ts:56:38)


 ✖ Home Page

   1) - Error in fixture.beforeEach hook -
      A request to "http://localhost:3200/" has failed.
      Use quarantine mode to perform additional attempts to execute this test.
      You can find troubleshooting information for this issue at "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".

      Error details:
      Failed to find a DNS-record for the resource at "http://localhost:3200/".

      Browser: Chrome 85.0.4183.121 / macOS 10.15.6

         29 |  studentMentorSpaceAskQuestionWidget,
         30 |  studentMentorSpaceMentorDirectoryWidget,
         31 |} from '../components/student/student-widget-names';
         32 |
         33 |export const adminLogin = async ({ email, password, browser }) => {
       > 34 |  await browser.click(Selector('div.ui.top.right.pointing.dropdown').child('div.text'));
         35 |  await browser.click(Selector('#admin'));
         36 |  await browser.typeText(Selector('input[name=email]'), email);
         37 |  await browser.typeText(Selector('input[name=password]'), password);
         38 |  await browser.click(Selector('div.field button.ui.button'));
         39 |};

         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/test-helpers/e2e.ts:34:17)
         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/test-helpers/e2e.ts:8:71)
         at __awaiter (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/test-helpers/e2e.ts:4:12)
         at Object.exports.adminLogin (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/test-helpers/e2e.ts:33:66)
         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/pages/student/StudentPages.test-e2e.ts:57:11)
         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/pages/student/StudentPages.test-e2e.ts:8:71)
         at __awaiter (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/pages/student/StudentPages.test-e2e.ts:4:12)
         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/pages/student/StudentPages.test-e2e.ts:56:38)


 ✖ Explorer Page

   1) - Error in fixture.beforeEach hook -
      A request to "http://localhost:3200/" has failed.
      Use quarantine mode to perform additional attempts to execute this test.
      You can find troubleshooting information for this issue at "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".

      Error details:
      Failed to find a DNS-record for the resource at "http://localhost:3200/".

      Browser: Chrome 85.0.4183.121 / macOS 10.15.6

         29 |  studentMentorSpaceAskQuestionWidget,
         30 |  studentMentorSpaceMentorDirectoryWidget,
         31 |} from '../components/student/student-widget-names';
         32 |
         33 |export const adminLogin = async ({ email, password, browser }) => {
       > 34 |  await browser.click(Selector('div.ui.top.right.pointing.dropdown').child('div.text'));
         35 |  await browser.click(Selector('#admin'));
         36 |  await browser.typeText(Selector('input[name=email]'), email);
         37 |  await browser.typeText(Selector('input[name=password]'), password);
         38 |  await browser.click(Selector('div.field button.ui.button'));
         39 |};

         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/test-helpers/e2e.ts:34:17)
         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/test-helpers/e2e.ts:8:71)
         at __awaiter (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/test-helpers/e2e.ts:4:12)
         at Object.exports.adminLogin (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/test-helpers/e2e.ts:33:66)
         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/pages/student/StudentPages.test-e2e.ts:57:11)
         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/pages/student/StudentPages.test-e2e.ts:8:71)
         at __awaiter (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/pages/student/StudentPages.test-e2e.ts:4:12)
         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/pages/student/StudentPages.test-e2e.ts:56:38)


 ✖ DEP Page

   1) - Error in fixture.beforeEach hook -
      A request to "http://localhost:3200/" has failed.
      Use quarantine mode to perform additional attempts to execute this test.
      You can find troubleshooting information for this issue at "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".

      Error details:
      Failed to find a DNS-record for the resource at "http://localhost:3200/".

      Browser: Chrome 85.0.4183.121 / macOS 10.15.6

         29 |  studentMentorSpaceAskQuestionWidget,
         30 |  studentMentorSpaceMentorDirectoryWidget,
         31 |} from '../components/student/student-widget-names';
         32 |
         33 |export const adminLogin = async ({ email, password, browser }) => {
       > 34 |  await browser.click(Selector('div.ui.top.right.pointing.dropdown').child('div.text'));
         35 |  await browser.click(Selector('#admin'));
         36 |  await browser.typeText(Selector('input[name=email]'), email);
         37 |  await browser.typeText(Selector('input[name=password]'), password);
         38 |  await browser.click(Selector('div.field button.ui.button'));
         39 |};

         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/test-helpers/e2e.ts:34:17)
         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/test-helpers/e2e.ts:8:71)
         at __awaiter (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/test-helpers/e2e.ts:4:12)
         at Object.exports.adminLogin (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/test-helpers/e2e.ts:33:66)
         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/pages/student/StudentPages.test-e2e.ts:57:11)
         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/pages/student/StudentPages.test-e2e.ts:8:71)
         at __awaiter (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/pages/student/StudentPages.test-e2e.ts:4:12)
         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/pages/student/StudentPages.test-e2e.ts:56:38)


 ✖ Mentor Space Page

   1) - Error in fixture.beforeEach hook -
      A request to "http://localhost:3200/" has failed.
      Use quarantine mode to perform additional attempts to execute this test.
      You can find troubleshooting information for this issue at "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".

      Error details:
      Failed to find a DNS-record for the resource at "http://localhost:3200/".

      Browser: Chrome 85.0.4183.121 / macOS 10.15.6

         29 |  studentMentorSpaceAskQuestionWidget,
         30 |  studentMentorSpaceMentorDirectoryWidget,
         31 |} from '../components/student/student-widget-names';
         32 |
         33 |export const adminLogin = async ({ email, password, browser }) => {
       > 34 |  await browser.click(Selector('div.ui.top.right.pointing.dropdown').child('div.text'));
         35 |  await browser.click(Selector('#admin'));
         36 |  await browser.typeText(Selector('input[name=email]'), email);
         37 |  await browser.typeText(Selector('input[name=password]'), password);
         38 |  await browser.click(Selector('div.field button.ui.button'));
         39 |};

         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/test-helpers/e2e.ts:34:17)
         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/test-helpers/e2e.ts:8:71)
         at __awaiter (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/test-helpers/e2e.ts:4:12)
         at Object.exports.adminLogin (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/test-helpers/e2e.ts:33:66)
         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/pages/student/StudentPages.test-e2e.ts:57:11)
         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/pages/student/StudentPages.test-e2e.ts:8:71)
         at __awaiter (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/pages/student/StudentPages.test-e2e.ts:4:12)
         at <anonymous> (/Users/philipjohnson/github/radgrad/radgrad2/app/imports/ui/pages/student/StudentPages.test-e2e.ts:56:38)



 5/5 failed (1s)
npm ERR! code ELIFECYCLE
npm ERR! errno 5
npm ERR! radgrad2@ test-e2e: `testcafe chrome:headless imports/ui/**/*.test-e2e.ts`
npm ERR! Exit status 5
npm ERR!
npm ERR! Failed at the radgrad2@ test-e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/philipjohnson/.npm/_logs/2020-10-03T01_18_18_082Z-debug.log
```

**Comment by philipmjohnson** [comment]
Accumulated questions:

  * radgrad2/app/tests/. This does not appear to be used. Can we delete it?
  * radgrad2/nightwatch.json.   Can we delete? 
  * radgrad2/dot.eslintrc-old. Can we delete?
  * radgrad2/package-lock.json. Can we delete (this is not the one in the app directory.)

**Comment by cammoore** [comment]
* Yes, it was old.
* Yes, again was using nightwatch for e2e testing at one point. Didn't like it.
* Yes, eslint settings are now in package.json
* Yes
* Wanted a way to get the names/ids of the components for e2e testing. Wanted a common place to put the names.
* Example drag-and-drop code. Was useful to refer to when building the Degree Planner and Academic Plan builder. Probably can get rid of it now.

**Comment by philipmjohnson** [comment]
Moved stuff to archive/, or deleted.

Acceptance tests now working. Although there aren't a lot of them.
