### ISSUE TITLE
Error: Cannot read property 'collectionViews' of undefined. Remove userCache package?

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#363]
Please do work for this task in a branch called issue-363.

After logging in as opq@hawaii.edu to radgrad1 on Dec 22, 2020, the following error gets generated:

```
TypeError: Cannot read property 'collectionViews' of undefined
    at _getCache (packages/msavin_usercache.js:31:130)
    at Object.Meteor.user (packages/msavin_usercache.js:74:15)
    at MethodInvocation.run (imports/api/user/StudentProfileCollection.methods.js:41:67)
    at ValidatedMethod._execute (packages/mdg:validated-method/validated-method.js:94:12)
    at MethodInvocation.StudentProfileCollection.getStudentProfile (packages/mdg:validated-method/validated-method.js:57:23)
    at MethodInvocation.methodMap.<computed> (packages/mdg:meteor-apm-agent/lib/hijack/wrap_session.js:161:30)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/mdg:meteor-apm-agent/lib/hijack/wrap_session.js:52:38
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
```

The Kadira APM page shows a little bit more:

<img width="1478" alt="Screen Shot 2020-12-22 at 9 18 13 AM" src="https://user-images.githubusercontent.com/290288/102925136-ef618300-4436-11eb-89e2-4821e2f3a6bb.png">

Here is the issue for the msavin/userCache package:

https://github.com/msavin/userCache/issues/5

Note that this package has been abandoned and we need to either replace with https://github.com/wildhart/userCache or move to https://atmospherejs.com/wildhart/mergebox-cache

This could be the reason that radgrad1 is hanging chronically.

**Comment by cammoore** [comment]
According to the RadGrad1 .meteor/packages msavin:usercache is needed for Galaxy Professional application performance monitoring. 

Since we aren't deploying RadGrad2 to Galaxy we probably don't need this package.
