### ISSUE TITLE
OpportunityTypeCollection unit test failed during test-unit.

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#372]
Please do work for this task in a branch called issue-372.

I20210123-21:16:42.595(0)?   1) OpportunityTypeCollection
I20210123-21:16:42.595(0)?        Can findDocBySlug:
I20210123-21:16:42.595(0)?      Error: [Attempt to redefine slug: et]
I20210123-21:16:42.595(0)?       at SlugCollection.define (imports/api/slug/SlugCollection.ts:57:13)
I20210123-21:16:42.596(0)?       at OpportunityTypeCollection.define (imports/api/base/BaseTypeCollection.ts:46:26)
I20210123-21:16:42.596(0)?       at OpportunityTypeCollection.define (imports/api/opportunity/OpportunityTypeCollection.ts:29:18)
I20210123-21:16:42.596(0)?       at Test.test (imports/api/opportunity/OpportunityTypeCollection.test.ts:110:24)
I20210123-21:16:42.596(0)?       at run (packages/meteortesting:mocha-core/server.js:36:29)

**Comment by cammoore** [comment]
Added the current date to the slugs.
