### ISSUE TITLE
Investigate Monti APM error.

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#511]
Please do work for this task in a branch called issue-XXX.
TypeError: Cannot read property 'grade' of undefined
    at meteor://💻app/imports/api/course/CourseUtilities.ts:172:122
    at meteor://💻app/imports/ui/pages/student/StudentDegreePlannerPage.tsx:270:12
    at Array.filter (<anonymous>:null:null)
    at meteor://💻app/imports/ui/pages/student/StudentDegreePlannerPage.tsx:267:34
    at meteor://💻app/packages/react-meteor-data/withTracker.tsx:17:36
    at meteor://💻app/packages/react-meteor-data/useTracker.ts:66:19
    at meteor://💻app/packages/tracker/tracker.js:308:38
    at apply (meteor://💻app/packages/montiapm:agent/lib/client/error_reporters/tracker.js:49:23)
    at _compute (meteor://💻app/packages/tracker/tracker.js:206:11)
    at meteor://💻app/packages/tracker/tracker.js:576:10

**Comment by cammoore** [comment]
It looks like we are trying to determine if a course instance is passed for an undefined course instance.
That's a profile course that the student hasn't taken. 

There are two things we should do:
 1. Don't try to determine if ci undefined is passed or is repeatable.
 2. Make the CourseUtilities functions more robust so they handle undefined parameters.
