### ISSUE TITLE
RadGradLoginButtons callback is not robust.

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#610]
Please do work for this task in a branch called issue-610.

We get Monti APM errors similar to:

Error: Exception in delivering result of invoking 'login': Cannot read property 'isAlumni' of undefined

    at meteor://💻app/imports/ui/components/landing/RadGradLoginButtons.tsx:35:22
    at userCallback (meteor://💻app/packages/accounts-base/accounts_client.js:235:16)
    at loginCallbacks (meteor://💻app/packages/accounts-base/accounts_client.js:358:6)
    at MethodInvoker._callback (https://radgrad2.ics.hawaii.edu/packages/meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:1234:22)
    at _callback (meteor://💻app/packages/ddp-client/common/MethodInvoker.js:52:11)
    at _maybeInvokeCallback (meteor://💻app/packages/ddp-client/common/MethodInvoker.js:79:9)
    at dataVisible (meteor://💻app/packages/ddp-client/common/livedata_connection.js:1354:37)
    at meteor://💻app/packages/ddp-client/common/livedata_connection.js:1221:7
    at Array.forEach (<anonymous>:null:null)

**Comment by cammoore** [comment]
Here's another example of an error we've gotten.

Error: Exception in delivering result of invoking 'login': Cannot read property 'toLowerCase' of undefined

    at toLowerCase (meteor://💻app/imports/ui/components/landing/RadGradLoginButtons.tsx:32:31)
    at userCallback (meteor://💻app/packages/accounts-base/accounts_client.js:235:16)
    at loginCallbacks (meteor://💻app/packages/accounts-base/accounts_client.js:358:6)
