### ISSUE TITLE
Loading a matriculated DB produces "user not defined" errors.

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#689]
Please do work for this task in a branch called issue-688.

I did the following:

1. Dumped the radgrad2.ics.hawaii.edu DB.
2. Loaded it into a local instance.
3. Ran the matriculation command.
4. Dumped the local DB, putting it into the custom directory.
5. Deleted the radgrad2.ics.hawaii.edu DB.
6. Set the databaseRestoreFileName property to the dumped matriculated DB.
7. Redeployed radgrad2.ics.hawaii.edu.

And I got these errors:

```
$ mup logs
[radgrad2.ics.hawaii.edu]=> Starting meteor app on port:3000
[radgrad2.ics.hawaii.edu]Monti APM: completed instrumenting the app
[radgrad2.ics.hawaii.edu]Startup:
[radgrad2.ics.hawaii.edu]  * Initializing admin user if necessary.
[radgrad2.ics.hawaii.edu]Defining admin radgrad@hawaii.edu with password JFPQDCwhn4eyRUPrp2n9uUYOrisD
[radgrad2.ics.hawaii.edu]  * Initializing database if necessary.
[radgrad2.ics.hawaii.edu]Loading database from file database/custom/2021-06-27-12-34-56.json, dumped 13 hours ago.
[radgrad2.ics.hawaii.edu]Defining 146 AcademicTermCollection documents.
[radgrad2.ics.hawaii.edu]Monti APM: Successfully connected
[radgrad2.ics.hawaii.edu]Have 146 documents.
[radgrad2.ics.hawaii.edu]Defining 3 InterestTypeCollection documents.
[radgrad2.ics.hawaii.edu]Have 3 documents.
[radgrad2.ics.hawaii.edu]Defining 78 InterestCollection documents.
[radgrad2.ics.hawaii.edu]Have 78 documents.
[radgrad2.ics.hawaii.edu]Defining 20 CareerGoalCollection documents.
[radgrad2.ics.hawaii.edu]Have 20 documents.
[radgrad2.ics.hawaii.edu]Defining 1 AdminProfileCollection documents.
[radgrad2.ics.hawaii.edu]Have 1 documents.
[radgrad2.ics.hawaii.edu]Defining 5 AdvisorProfileCollection documents.
[radgrad2.ics.hawaii.edu]Have 5 documents.
[radgrad2.ics.hawaii.edu]Defining 21 FacultyProfileCollection documents.
[radgrad2.ics.hawaii.edu]Have 21 documents.
[radgrad2.ics.hawaii.edu]Defining 5 OpportunityTypeCollection documents.
[radgrad2.ics.hawaii.edu]Have 5 documents.
[radgrad2.ics.hawaii.edu]Defining 109 OpportunityCollection documents.
[radgrad2.ics.hawaii.edu]Have 109 documents.
[radgrad2.ics.hawaii.edu]Defining 131 CourseCollection documents.
[radgrad2.ics.hawaii.edu]Have 131 documents.
[radgrad2.ics.hawaii.edu]Defining 71 TeaserCollection documents.
[radgrad2.ics.hawaii.edu]Have 71 documents.
[radgrad2.ics.hawaii.edu]Defining 719 StudentProfileCollection documents.
[radgrad2.ics.hawaii.edu]Have 719 documents.
[radgrad2.ics.hawaii.edu]Defining 9719 CourseInstanceCollection documents.
[radgrad2.ics.hawaii.edu]Have 9719 documents.
[radgrad2.ics.hawaii.edu]Defining 2631 OpportunityInstanceCollection documents.
[radgrad2.ics.hawaii.edu]Have 2631 documents.
[radgrad2.ics.hawaii.edu]Defining 642 VerificationRequestCollection documents.
[radgrad2.ics.hawaii.edu]Have 642 documents.
[radgrad2.ics.hawaii.edu]Defining 779 UserInteractionCollection documents.
[radgrad2.ics.hawaii.edu]Have 779 documents.
[radgrad2.ics.hawaii.edu]Defining 142 ReviewCollection documents.
[radgrad2.ics.hawaii.edu]Have 142 documents.
[radgrad2.ics.hawaii.edu]Defining 1510 ProfileCareerGoalCollection documents.
[radgrad2.ics.hawaii.edu]Have 1510 documents.
[radgrad2.ics.hawaii.edu]Defining 8816 ProfileCourseCollection documents.
[radgrad2.ics.hawaii.edu]Have 8816 documents.
[radgrad2.ics.hawaii.edu]Defining 2724 ProfileInterestCollection documents.
[radgrad2.ics.hawaii.edu]Have 2724 documents.
[radgrad2.ics.hawaii.edu]Defining 1976 ProfileOpportunityCollection documents.
[radgrad2.ics.hawaii.edu]Have 1976 documents.
[radgrad2.ics.hawaii.edu]Finished loading database.
[radgrad2.ics.hawaii.edu]  * Initializing public stats.
[radgrad2.ics.hawaii.edu]  * Initializing factoids.
[radgrad2.ics.hawaii.edu]  * Initializing whats new
[radgrad2.ics.hawaii.edu]  * Initializing user interaction manager
[radgrad2.ics.hawaii.edu]  * Initializing cron jobs
[radgrad2.ics.hawaii.edu]  * Initializing forecasts
[radgrad2.ics.hawaii.edu]UserInteractionManager.dailyUpdate(): new Interactions:  86
[radgrad2.ics.hawaii.edu]Error: user is not defined:  C7xkZTov9SSFuHGnm
[radgrad2.ics.hawaii.edu]Exception from sub AcademicYearInstanceCollection id d8HwXde5ZDWwuMDMz TypeError: Cannot read property '_id' of undefined
[radgrad2.ics.hawaii.edu]    at UserCollection.getID (imports/api/user/UserCollection.ts:156:20)
[radgrad2.ics.hawaii.edu]    at UserCollection.hasProfile (imports/api/user/UserCollection.ts:218:25)
[radgrad2.ics.hawaii.edu]    at UserCollection.getProfile (imports/api/user/UserCollection.ts:305:26)
[radgrad2.ics.hawaii.edu]    at Subscription.filterStudentID [as _handler] (imports/api/degree-plan/AcademicYearInstanceCollection.ts:184:31)
[radgrad2.ics.hawaii.edu]    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
[radgrad2.ics.hawaii.edu]    at packages/ddp-server/livedata_server.js:1046:15
[radgrad2.ics.hawaii.edu]    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
[radgrad2.ics.hawaii.edu]    at Subscription._runHandler (packages/ddp-server/livedata_server.js:1044:51)
[radgrad2.ics.hawaii.edu]    at Subscription.subscriptionProto._runHandler (packages/montiapm:agent/lib/hijack/wrap_subscription.js:12:24)
[radgrad2.ics.hawaii.edu]    at Session._startSubscription (packages/ddp-server/livedata_server.js:860:9)
[radgrad2.ics.hawaii.edu]    at Session.sub (packages/ddp-server/livedata_server.js:625:12)
[radgrad2.ics.hawaii.edu]    at packages/montiapm:agent/lib/hijack/wrap_session.js:90:34
[radgrad2.ics.hawaii.edu]    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
[radgrad2.ics.hawaii.edu]    at Session.sessionProto.protocol_handlers.sub (packages/montiapm:agent/lib/hijack/wrap_session.js:89:44)
[radgrad2.ics.hawaii.edu]    at packages/ddp-server/livedata_server.js:559:43
[radgrad2.ics.hawaii.edu]Error: user is not defined:  C7xkZTov9SSFuHGnm
[radgrad2.ics.hawaii.edu]Exception from sub CourseInstanceCollection id wjxhkKupPh4MtCkfa TypeError: Cannot read property '_id' of undefined
[radgrad2.ics.hawaii.edu]    at UserCollection.getID (imports/api/user/UserCollection.ts:156:20)
[radgrad2.ics.hawaii.edu]    at UserCollection.hasProfile (imports/api/user/UserCollection.ts:218:25)
[radgrad2.ics.hawaii.edu]    at UserCollection.getProfile (imports/api/user/UserCollection.ts:305:26)
[radgrad2.ics.hawaii.edu]    at Subscription.filterStudentID [as _handler] (imports/api/course/CourseInstanceCollection.ts:391:31)
[radgrad2.ics.hawaii.edu]    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
[radgrad2.ics.hawaii.edu]    at packages/ddp-server/livedata_server.js:1046:15
[radgrad2.ics.hawaii.edu]    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
[radgrad2.ics.hawaii.edu]    at Subscription._runHandler (packages/ddp-server/livedata_server.js:1044:51)
[radgrad2.ics.hawaii.edu]    at Subscription.subscriptionProto._runHandler (packages/montiapm:agent/lib/hijack/wrap_subscription.js:12:24)
[radgrad2.ics.hawaii.edu]    at Session._startSubscription (packages/ddp-server/livedata_server.js:860:9)
[radgrad2.ics.hawaii.edu]    at Session.sub (packages/ddp-server/livedata_server.js:625:12)
[radgrad2.ics.hawaii.edu]    at packages/montiapm:agent/lib/hijack/wrap_session.js:90:34
[radgrad2.ics.hawaii.edu]    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
[radgrad2.ics.hawaii.edu]    at Session.sessionProto.protocol_handlers.sub (packages/montiapm:agent/lib/hijack/wrap_session.js:89:44)
[radgrad2.ics.hawaii.edu]    at packages/ddp-server/livedata_server.js:559:43
[radgrad2.ics.hawaii.edu]Error: user is not defined:  C7xkZTov9SSFuHGnm
[radgrad2.ics.hawaii.edu]Exception from sub OpportunityInstanceCollection id x6ePzv4c8uZ9gYHE9 TypeError: Cannot read property '_id' of undefined
[radgrad2.ics.hawaii.edu]    at UserCollection.getID (imports/api/user/UserCollection.ts:156:20)
[radgrad2.ics.hawaii.edu]    at UserCollection.hasProfile (imports/api/user/UserCollection.ts:218:25)
[radgrad2.ics.hawaii.edu]    at UserCollection.getProfile (imports/api/user/UserCollection.ts:305:26)
[radgrad2.ics.hawaii.edu]    at Subscription.filterStudent [as _handler] (imports/api/opportunity/OpportunityInstanceCollection.ts:278:31)
[radgrad2.ics.hawaii.edu]    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
[radgrad2.ics.hawaii.edu]    at packages/ddp-server/livedata_server.js:1046:15
[radgrad2.ics.hawaii.edu]    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
[radgrad2.ics.hawaii.edu]    at Subscription._runHandler (packages/ddp-server/livedata_server.js:1044:51)
[radgrad2.ics.hawaii.edu]    at Subscription.subscriptionProto._runHandler (packages/montiapm:agent/lib/hijack/wrap_subscription.js:12:24)
[radgrad2.ics.hawaii.edu]    at Session._startSubscription (packages/ddp-server/livedata_server.js:860:9)
[radgrad2.ics.hawaii.edu]    at Session.sub (packages/ddp-server/livedata_server.js:625:12)
[radgrad2.ics.hawaii.edu]    at packages/montiapm:agent/lib/hijack/wrap_session.js:90:34
[radgrad2.ics.hawaii.edu]    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
[radgrad2.ics.hawaii.edu]    at Session.sessionProto.protocol_handlers.sub (packages/montiapm:agent/lib/hijack/wrap_session.js:89:44)
[radgrad2.ics.hawaii.edu]    at packages/ddp-server/livedata_server.js:559:43
[radgrad2.ics.hawaii.edu]Error: user is not defined:  C7xkZTov9SSFuHGnm
[radgrad2.ics.hawaii.edu]Exception from sub ProfileCareerGoalCollection id YCykdwcLRYSxMrLC4 TypeError: Cannot read property '_id' of undefined
[radgrad2.ics.hawaii.edu]    at UserCollection.getID (imports/api/user/UserCollection.ts:156:20)
[radgrad2.ics.hawaii.edu]    at UserCollection.hasProfile (imports/api/user/UserCollection.ts:218:25)
[radgrad2.ics.hawaii.edu]    at UserCollection.getProfile (imports/api/user/UserCollection.ts:305:26)
[radgrad2.ics.hawaii.edu]    at Subscription.filterStudentID [as _handler] (imports/api/user/profile-entries/ProfileCareerGoalCollection.ts:84:31)
[radgrad2.ics.hawaii.edu]    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
[radgrad2.ics.hawaii.edu]    at packages/ddp-server/livedata_server.js:1046:15
[radgrad2.ics.hawaii.edu]    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
[radgrad2.ics.hawaii.edu]    at Subscription._runHandler (packages/ddp-server/livedata_server.js:1044:51)
[radgrad2.ics.hawaii.edu]    at Subscription.subscriptionProto._runHandler (packages/montiapm:agent/lib/hijack/wrap_subscription.js:12:24)
[radgrad2.ics.hawaii.edu]    at Session._startSubscription (packages/ddp-server/livedata_server.js:860:9)
[radgrad2.ics.hawaii.edu]    at Session.sub (packages/ddp-server/livedata_server.js:625:12)
[radgrad2.ics.hawaii.edu]    at packages/montiapm:agent/lib/hijack/wrap_session.js:90:34
[radgrad2.ics.hawaii.edu]    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
[radgrad2.ics.hawaii.edu]    at Session.sessionProto.protocol_handlers.sub (packages/montiapm:agent/lib/hijack/wrap_session.js:89:44)
[radgrad2.ics.hawaii.edu]    at packages/ddp-server/livedata_server.js:559:43
[radgrad2.ics.hawaii.edu]Error: user is not defined:  C7xkZTov9SSFuHGnm
[radgrad2.ics.hawaii.edu]Exception from sub ProfileCourseCollection id 9mqqwKJPdG4YfhkrW TypeError: Cannot read property '_id' of undefined
[radgrad2.ics.hawaii.edu]    at UserCollection.getID (imports/api/user/UserCollection.ts:156:20)
[radgrad2.ics.hawaii.edu]    at UserCollection.hasProfile (imports/api/user/UserCollection.ts:218:25)
[radgrad2.ics.hawaii.edu]    at UserCollection.getProfile (imports/api/user/UserCollection.ts:305:26)
[radgrad2.ics.hawaii.edu]    at Subscription.filterStudentID [as _handler] (imports/api/user/profile-entries/ProfileCourseCollection.ts:82:31)
[radgrad2.ics.hawaii.edu]    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
[radgrad2.ics.hawaii.edu]    at packages/ddp-server/livedata_server.js:1046:15
[radgrad2.ics.hawaii.edu]    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
[radgrad2.ics.hawaii.edu]    at Subscription._runHandler (packages/ddp-server/livedata_server.js:1044:51)
[radgrad2.ics.hawaii.edu]    at Subscription.subscriptionProto._runHandler (packages/montiapm:agent/lib/hijack/wrap_subscription.js:12:24)
[radgrad2.ics.hawaii.edu]    at Session._startSubscription (packages/ddp-server/livedata_server.js:860:9)
[radgrad2.ics.hawaii.edu]    at Session.sub (packages/ddp-server/livedata_server.js:625:12)
[radgrad2.ics.hawaii.edu]    at packages/montiapm:agent/lib/hijack/wrap_session.js:90:34
[radgrad2.ics.hawaii.edu]    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
[radgrad2.ics.hawaii.edu]    at Session.sessionProto.protocol_handlers.sub (packages/montiapm:agent/lib/hijack/wrap_session.js:89:44)
[radgrad2.ics.hawaii.edu]    at packages/ddp-server/livedata_server.js:559:43
[radgrad2.ics.hawaii.edu]Error: user is not defined:  C7xkZTov9SSFuHGnm
[radgrad2.ics.hawaii.edu]Exception from sub ProfileInterestCollection id w4cdcumgKiMYNQhp9 TypeError: Cannot read property '_id' of undefined
[radgrad2.ics.hawaii.edu]    at UserCollection.getID (imports/api/user/UserCollection.ts:156:20)
[radgrad2.ics.hawaii.edu]    at UserCollection.hasProfile (imports/api/user/UserCollection.ts:218:25)
[radgrad2.ics.hawaii.edu]    at UserCollection.getProfile (imports/api/user/UserCollection.ts:305:26)
[radgrad2.ics.hawaii.edu]    at Subscription.filterStudentID [as _handler] (imports/api/user/profile-entries/ProfileInterestCollection.ts:83:31)
[radgrad2.ics.hawaii.edu]    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
[radgrad2.ics.hawaii.edu]    at packages/ddp-server/livedata_server.js:1046:15
[radgrad2.ics.hawaii.edu]    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
[radgrad2.ics.hawaii.edu]    at Subscription._runHandler (packages/ddp-server/livedata_server.js:1044:51)
[radgrad2.ics.hawaii.edu]    at Subscription.subscriptionProto._runHandler (packages/montiapm:agent/lib/hijack/wrap_subscription.js:12:24)
[radgrad2.ics.hawaii.edu]    at Session._startSubscription (packages/ddp-server/livedata_server.js:860:9)
[radgrad2.ics.hawaii.edu]    at Session.sub (packages/ddp-server/livedata_server.js:625:12)
[radgrad2.ics.hawaii.edu]    at packages/montiapm:agent/lib/hijack/wrap_session.js:90:34
[radgrad2.ics.hawaii.edu]    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
[radgrad2.ics.hawaii.edu]    at Session.sessionProto.protocol_handlers.sub (packages/montiapm:agent/lib/hijack/wrap_session.js:89:44)
[radgrad2.ics.hawaii.edu]    at packages/ddp-server/livedata_server.js:559:43
[radgrad2.ics.hawaii.edu]Error: user is not defined:  C7xkZTov9SSFuHGnm
[radgrad2.ics.hawaii.edu]Exception from sub ProfileOpportunityCollection id 3yCWqgzkQACWE45gk TypeError: Cannot read property '_id' of undefined
[radgrad2.ics.hawaii.edu]    at UserCollection.getID (imports/api/user/UserCollection.ts:156:20)
[radgrad2.ics.hawaii.edu]    at UserCollection.hasProfile (imports/api/user/UserCollection.ts:218:25)
[radgrad2.ics.hawaii.edu]    at UserCollection.getProfile (imports/api/user/UserCollection.ts:305:26)
[radgrad2.ics.hawaii.edu]    at Subscription.filterStudentID [as _handler] (imports/api/user/profile-entries/ProfileOpportunityCollection.ts:82:31)
[radgrad2.ics.hawaii.edu]    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
[radgrad2.ics.hawaii.edu]    at packages/ddp-server/livedata_server.js:1046:15
[radgrad2.ics.hawaii.edu]    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
[radgrad2.ics.hawaii.edu]    at Subscription._runHandler (packages/ddp-server/livedata_server.js:1044:51)
[radgrad2.ics.hawaii.edu]    at Subscription.subscriptionProto._runHandler (packages/montiapm:agent/lib/hijack/wrap_subscription.js:12:24)
[radgrad2.ics.hawaii.edu]    at Session._startSubscription (packages/ddp-server/livedata_server.js:860:9)
[radgrad2.ics.hawaii.edu]    at Session.sub (packages/ddp-server/livedata_server.js:625:12)
[radgrad2.ics.hawaii.edu]    at packages/montiapm:agent/lib/hijack/wrap_session.js:90:34
[radgrad2.ics.hawaii.edu]    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
[radgrad2.ics.hawaii.edu]    at Session.sessionProto.protocol_handlers.sub (packages/montiapm:agent/lib/hijack/wrap_session.js:89:44)
[radgrad2.ics.hawaii.edu]    at packages/ddp-server/livedata_server.js:559:43
```

**Comment by philipmjohnson** [comment]
Not a matriculation problem; was due to a user being logged in and not logged off while the DB changed underneath them.
